<a href="https://colab.research.google.com/github/jenous11/FYP-Cyberbullying-Test-Classification-/blob/main/workingwithkaggle_parsed_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from google.colab import files
uploaded_files=files.upload()

Saving kaggle_parsed_dataset.csv to kaggle_parsed_dataset.csv

In [5]:
kaggle_df=pd.read_csv("kaggle_parsed_dataset.csv")

In [6]:
kaggle_df.head(5)

,index,oh_label,Date,Text
0,0,1,20120618192155Z,"""You fuck your dad."""
1,1,0,20120528192215Z,"""i really don't understand your point.\xa0 It ..."
2,2,0,NaN,"""A\\xc2\\xa0majority of Canadians can and has ..."
3,3,0,NaN,"""listen if you dont wanna get married to a man..."
4,4,0,20120619094753Z,"""C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd..."

In [7]:
kaggle_df.isnull().sum()

index          0
oh_label       0
Date        1242
Text           0
dtype: int64

In [8]:
print(kaggle_df.shape)

(8799, 4)

In [9]:
# checking for missing data

print("Missing Text:", kaggle_df['Text'].isna().sum())
print("\nLabel distribution:\n")
print(kaggle_df['oh_label'].value_counts())

Missing Text: 0

Label distribution:

oh_label
0    5993
1    2806
Name: count, dtype: int64

In [10]:
#cleaning the empty cells

In [11]:
kaggle_clean=kaggle_df[['Text','oh_label']].copy()

In [12]:
# kaggle_clean=kaggle_clean.dropna(subset=['Text','oh_label'])
kaggle_clean=kaggle_clean.dropna(subset=['Text','oh_label'])
kaggle_clean

                                                   Text  oh_label
0                                  "You fuck your dad."         1
1     "i really don't understand your point.\xa0 It ...         0
2     "A\\xc2\\xa0majority of Canadians can and has ...         0
3     "listen if you dont wanna get married to a man...         0
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...         0
...                                                 ...       ...
8794  "Never really gave it much thought. I just fig...         0
8795                 "Nadie se salva de la regla 34 xd"         0
8796               "Question: Are you a boy or a girl?"         0
8797  "Leave your email or phone number and maybe yo...         1
8798  "From the scenarios you present, I see you bel...         0

[8799 rows x 2 columns]

In [13]:
kaggle_clean=kaggle_clean.rename(columns={'oh_label':'label'})
kaggle_clean

                                                   Text  label
0                                  "You fuck your dad."      1
1     "i really don't understand your point.\xa0 It ...      0
2     "A\\xc2\\xa0majority of Canadians can and has ...      0
3     "listen if you dont wanna get married to a man...      0
4     "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...      0
...                                                 ...    ...
8794  "Never really gave it much thought. I just fig...      0
8795                 "Nadie se salva de la regla 34 xd"      0
8796               "Question: Are you a boy or a girl?"      0
8797  "Leave your email or phone number and maybe yo...      1
8798  "From the scenarios you present, I see you bel...      0

[8799 rows x 2 columns]

In [14]:
# kaggle_clean.shape
kaggle_clean.isna().sum()

Text     0
label    0
dtype: int64

In [15]:
kaggle_clean['Text']

0                                    "You fuck your dad."
1       "i really don't understand your point.\xa0 It ...
2       "A\\xc2\\xa0majority of Canadians can and has ...
3       "listen if you dont wanna get married to a man...
4       "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...
                              ...
8794    "Never really gave it much thought. I just fig...
8795                   "Nadie se salva de la regla 34 xd"
8796                 "Question: Are you a boy or a girl?"
8797    "Leave your email or phone number and maybe yo...
8798    "From the scenarios you present, I see you bel...
Name: Text, Length: 8799, dtype: object

In [16]:
kaggle_clean['Text']

0                                    "You fuck your dad."
1       "i really don't understand your point.\xa0 It ...
2       "A\\xc2\\xa0majority of Canadians can and has ...
3       "listen if you dont wanna get married to a man...
4       "C\xe1c b\u1ea1n xu\u1ed1ng \u0111\u01b0\u1edd...
                              ...
8794    "Never really gave it much thought. I just fig...
8795                   "Nadie se salva de la regla 34 xd"
8796                 "Question: Are you a boy or a girl?"
8797    "Leave your email or phone number and maybe yo...
8798    "From the scenarios you present, I see you bel...
Name: Text, Length: 8799, dtype: object

In [17]:
# now genarating a function

import re

def clean_text(data):

  result0 = re.sub(r'x[a-z0-9\s]+[\d]+'," ",data)

  # checking
  result = re.sub(r'https?[\S]+', " ", result0)
  partiallycleaned_result=result
  partiallycleaned_result

  #checking
  fully_cleaned_result=re.sub(r' @[a-zA-Z0-9]+'," ",partiallycleaned_result)
  fully_cleaned_result

 #remove special characters
  fully_cleaned_result = re.sub(r'\W+'," ",fully_cleaned_result)
  cleaned_data= fully_cleaned_result.strip().lower()
  return cleaned_data


#passing data to the function

# data="@ShreyaBafna3 You are SO stupid!! Check http://somelink.com \xc2\xa0"
data="Check http://somelink.com you are stupid /xa0 1212 "
clean_text(data)

'check you are stupid'

In [18]:
kaggle_clean['Text'] = kaggle_clean['Text'].apply(clean_text)

In [19]:
kaggle_clean['Text']

0                                       you fuck your dad
1       i really don t understand your point it seems ...
2       a majority of canadians can and has been wrong...
3       listen if you dont wanna get married to a man ...
4       c c b u1ea1n xu u1ed1ng u0111 u01b0 u1eddng bi...
                              ...
8794    never really gave it much thought i just figur...
8795                     nadie se salva de la regla 34 xd
8796                     question are you a boy or a girl
8797    leave your email or phone number and maybe you...
8798    from the scenarios you present i see you belie...
Name: Text, Length: 8799, dtype: object

In [20]:
kaggle_clean.head()

                                                Text  label
0                                  you fuck your dad      1
1  i really don t understand your point it seems ...      0
2  a majority of canadians can and has been wrong...      0
3  listen if you dont wanna get married to a man ...      0
4  c c b u1ea1n xu u1ed1ng u0111 u01b0 u1eddng bi...      0

In [21]:
kaggle_clean['Text'][8798]

'from the scenarios you present i see you believe all people are robots abraham no matter his environment or upbringing chose to aim his gun at the poor guy he killed and he chose to pull the trigger he has a bad childhood so let s understand why he would kill someone nwhen he s older he doesn t have the sense to realize that going before the judge you might want to appear humble and show some respect two things by the way that wasn t taught to him as a child and appears as a man is not important to him again his choice nhe knows selling drugs is wrong and could land him back in jail again a stupid premeditated decision on his part and he will be in jail shortly after he gets out because that s what a stupid unteachable hardened piece of clay does turn down the same road n nand you re right i am saying all this from my perspective like i said in my other comment most people could be put in abraham s exact shoes and they won t raise a gun and shoot that poor man dead nhumans not robots'

importing nltk libraries for text stopword removal

In [22]:
import nltk

nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Modifyig the regex function by adding stpword removal from nltk

In [23]:

def clean_text(data):
  if data is None:
        return ""

  result0 = re.sub(r'x[a-z0-9\s]+[\d]+'," ",data)
  # checking
  result = re.sub(r'https?[\S]+', " ", result0)
  partiallycleaned_result=result
  partiallycleaned_result
  #checking
  fully_cleaned_result=re.sub(r' @[a-zA-Z0-9]+'," ",partiallycleaned_result)
  fully_cleaned_result
  #remove special characters
  fully_cleaned_result = re.sub(r'\W+'," ",fully_cleaned_result)
  cleaned_data = fully_cleaned_result.strip().lower()
  # return cleaned_data
  # print(f"No stopword removal : {cleaned_data}")

  #getting set of english stopwords for efficient look up
  stop_words = set(stopwords.words('english'))
  word_tokens = [word for word in word_tokenize(cleaned_data)]
  filtered_sentence = [word for word in word_tokens if word not in stop_words]
  filtered_text = " ".join(filtered_sentence)

  #returnes filtered data with no stopwords
  # print(f"After stopword removal : {filtered_text}")
  return filtered_text
  #passing data to the function

# data="@ShreyaBafna3 You are SO stupid!! Check http://somelink.com \xc2\xa0"
# data="you are so stupid and the world is a bad place"
# clean_text(data)

In [24]:
kaggle_clean['Text']=kaggle_clean['Text'].apply(clean_text)

In [25]:
kaggle_clean.head()

                                                Text  label
0                                           fuck dad      1
1  really understand point seems mixing apples or...      0
2  majority canadians wrong n nunless supportive ...      0
3  listen dont wan na get married man women dont ...      0
4                                       c c b u1ea1n      0

added a vietnamese filter (removes too short after cleaning,non-english,and empty rows)

In [26]:
kaggle_clean = kaggle_clean[kaggle_clean['Text'].str.split().str.len() > 3]
print("Final shape:", kaggle_clean.shape)

Final shape: (7275, 2)

TF-IDF

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer= TfidfVectorizer()
X=vectorizer.fit_transform(kaggle_clean['Text'])
vectorizer.get_feature_names_out()
print(X.shape)

(7275, 21972)

In [31]:
kaggle_clean['label']

1       0
2       0
3       0
4       0
5       0
       ..
8793    0
8794    0
8795    0
8797    1
8798    0
Name: label, Length: 7275, dtype: int64

Importing Train and Test

In [33]:
from sklearn.model_selection import train_test_split
y= kaggle_clean['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
#shape of X_train and X_test
X_train.shape

(5820, 21972)

In [38]:
X_test.shape

(1455, 21972)